DokumaProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HomePage.urls')),
    path('login', include('LoginPage.urls')),
    path('register', include('RegisterPage.urls')),
]

HomePage/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='home'),
    path('mulai', views.mulai, name='mulai'),
]

LoginPage/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
]

RegisterPage/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('', views.register, name='register'),
    path('sudahlogin', views.register, name='already_login')
]

RegisterPage/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

class MyUserManager(BaseUserManager):
	def create_user(self, email, username, password=None):
		if not email:
			raise ValueError('Users must have an email address')
		if not username:
			raise ValueError('Users must have a username')

		user = self.model(
			email=self.normalize_email(email),
			username=username,
		)

		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_superuser(self, email, username, password):
		user = self.create_user(
			email=self.normalize_email(email),
			password=password,
			username=username,
		)
		user.is_admin = True
		user.is_staff = True
		user.is_superuser = True
		user.save(using=self._db)
		return user

# Create your models here.
class User(AbstractBaseUser):
    email                   = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username                = models.CharField(max_length=100, unique=True)
    date_joined             = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login              = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin                = models.BooleanField(default=False)
    is_active               = models.BooleanField(default=True)
    is_staff                = models.BooleanField(default=False)
    is_superuser            = models.BooleanField(default=False)
    hide_email              = models.BooleanField(default=True)
    nomor_str               = models.CharField(max_length=50)
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = MyUserManager()

    def str(self):
        return self.username

    # For checking permissions. to keep it simple all admin have ALL permissons
    def has_perm(self, perm, obj=None):
        return self.is_admin

    # Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)
    def has_module_perms(self, app_label):
        return True

RegisterPage/forms.py
from .models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms

class RegistrationForm(UserCreationForm):
	email = forms.EmailField(max_length=254, help_text='Required. Add a valid email address.')

	class Meta:
		model = User
		fields = ('email', 'username', 'password1', 'password2', 'nomor_str')

	def clean_email(self):
		email = self.cleaned_data['email'].lower()
		try:
			user = User.objects.exclude(pk=self.instance.pk).get(email=email)
		except User.DoesNotExist:
			return email
		raise forms.ValidationError('Email "%s" is already in use.' % email)

	def clean_username(self):
		username = self.cleaned_data['username']
		try:
			user = User.objects.exclude(pk=self.instance.pk).get(username=username)
		except User.DoesNotExist:
			return username
		raise forms.ValidationError('Username "%s" is already in use.' % username)

RegisterPage/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .forms import RegistrationForm

# Create your views here.
def register(request):
    user = request.user
    if user.is_authenticated:
        return render(request, 'already_login.html')
    context = {}

    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        data = {}
        if form.is_valid():
            print("berhasil")
            form.save()
            email = form.cleaned_data['email']
            password = form.cleaned_data['password1']
            user = authenticate(email=email, password=password)
            login(request, user)
            data['success'] = True
            return redirect('home:home')
        else:
            print("gagal asw")
            data['error'] = form.errors
            context['registration_form'] = form
            data['success'] = False
    else:
        form = RegistrationForm()
        context['registration_form'] = form

    return render(request, 'register.html', context)
    
def already_login(request):
    return render(request, 'already_login.html')

RegisterPage/templates/already_login.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
Dokuma
{% endblock %}


{% block content %}
<!-- ======= Header ======= -->
<header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">
        
        <h1 class="logo me-auto"><a href="{% url 'home:home' %}">Dokuma</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

        <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
            <li><a class="nav-link scrollto" style="color:#333399" href="{% url 'home:home' %}">Home</a></li>
            <!-- <li><a class="nav-link scrollto" href="#about">About</a></li>
            <li><a class="nav-link scrollto" href="#services">Services</a></li>
            <li><a class="nav-link scrollto" href="#departments">Departments</a></li>
            <li><a class="nav-link scrollto" href="#doctors">Doctors</a></li>
            <li><a class="nav-link scrollto" href="#contact">Contact</a></li> -->
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->
    </div>
</header><!-- End Header -->
<!-- ======= Appointment Section ======= -->
<section id="appointment" class="appointment section-bg">
    <div class="container">
        <div class="section-title">
            <br><br><br><br>
            <h2>Anda sudah login</h2>
        </div>
    </div>
</section><!-- End Appointment Section -->
{% endblock %}

RegisterPage/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Dokuma
{% endblock %}

{% block css %}
<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/sweetalert2@10.10.1/dist/sweetalert2.min.css'>
{% endblock %}


{% block content %}
<!-- ======= Header ======= -->
<header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">
        
        <h1 class="logo me-auto"><a href="{% url 'home:home' %}">Dokuma</a></h1>
        <a href="{% url 'home:home' %}" class="appointment-btn scrollto"><span class="d-none d-md-inline"></span> Home </a>
        <a href="{% url 'login:login' %}" class="appointment-btn scrollto"><span class="d-none d-md-inline"></span> Login </a>
    </div>
</header><!-- End Header -->
<!-- ======= Appointment Section ======= -->
<section id="appointment" class="appointment section-bg">
    <div class="container">
        <div class="section-title">
            <br><br><br>
            <h4>Let's Help People!</h4>
            <h2>Daftar Akun</h2>
        </div>

        <form action="" method="POST" role="form" id="signup-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-3 form-group mt-3">
                </div>
                <div class="col-md-6 form-group mt-3">
                    <input type="text" name="username" class="form-control" id="username" placeholder="Nama Dokter" required>
                    <div class="validate"></div>
                </div>
                <div class="col-md-3 form-group mt-3">
                </div>
            </div>

            <div class="row">
                <div class="col-md-3 form-group mt-3"></div>
                <div class="col-md-6 form-group mt-3 ">
                    <input type="text" name="nomor_str" class="form-control" id="nomor_str" data-rule="minlen:4" placeholder="Nomor STR" required>
                    <div class="validate"></div>
                </div>
                <div class="col-md-3 form-group mt-3"></div>
            </div>
            
            <div class="row">
                <div class="col-md-3 form-group mt-3">
                </div>
                <div class="col-md-6 form-group mt-3">
                    <input type="email" name="email" class="form-control" id="email" placeholder="Email" required>
                    <div class="validate"></div>
                </div>
                <div class="col-md-3 form-group mt-3">
                </div>
            </div>

            <div class="row">
                <div class="col-md-3 form-group mt-3"></div>
                <div class="col-md-6 form-group mt-3">
                    <input type="password" name="password1" class="form-control" id="password1" placeholder="Password" required>
                    <div class="validate"></div>
                </div>
                <div class="col-md-3 form-group mt-3"></div>
            </div>

            <div class="row">
                <div class="col-md-3 form-group mt-3"></div>
                <div class="col-md-6 form-group mt-3">
                    <input type="password" name="password2" class="form-control" id="password2" placeholder="Confirm Password" required>
                    <div class="validate"></div>
                </div>
                <div class="col-md-3 form-group mt-3"></div>
            </div>
            
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6 form-group mt-3" align="center">
                    <p id="error" style="color: red"></p>
                    {% for field in registration_form %}
                        <p>
                        {% for error in field.errors %}
                            <p style="color: red">{{ error }}</p>
                        {% endfor %}
                        </p>
                    {% endfor %}
                    
                    {% if registration_form.non_field_errors %}
                        <div style="color: red">
                            <p>{{registration_form.non_field_errors}}</p>
                        </div>
                    {% endif %}
                </div>
                <div class="col-md-3"></div>
            </div>


            <div class="text-center" ><button type="submit" style="background-color:#703757"; margin: 7px" class="btn btn-primary">Daftar</button></div>
        
            <div class="text-center">Sudah punya akun? Yuk <a href="{% url 'login:login' %}" style="color:#333399"><strong>masuk</strong></a></div>
        </form>
    </div>
</section><!-- End Appointment Section -->
{% endblock %}

{% block js %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.5.0.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>
<!-- <script type="text/javascript">
$(document).on('submit', '#signup-form', function(e){
    e.preventDefault();
    
    var signup_form_id = $('#signup-form')

    $.ajax({
        type:'POST',
        url:"{% url 'register:register' %}",
        data:signup_form_id.serialize(),
        dataType:"json",
        header: {'X-CSRFToken': '{% csrf_token %}'},
        success: function(response){
        var success = response['success']
            if (success){
                alert("Anda berhasil terdaftar! Silahkan login.")
            }
            else {
                alert("Pendaftaran akun gagal! Silakan coba lagi.");
                for(var msg in response['error']) {
                    var txt = JSON.stringify(response['error'][msg]);
                    document.getElementById("error").innerHTML = txt.replace(/[&\/\\#,\]+()$~%['":*?<>{}]/g, '');
                }
            }
        },
    });
});
</script> -->
{% endblock %}