DokumaProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HomePage.urls')),
    path('login', include('LoginPage.urls')),
    path('register', include('RegisterPage.urls')),
]

HomePage/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='home'),
    path('mulai', views.mulai, name='mulai'),
]

LoginPage/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
]

RegisterPage/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('', views.register, name='register'),
    path('sudahlogin', views.register, name='already_login')
]

HomePage/models.py
from django.db import models

# Create your models here.
# class IMAGE(models.Model):
#     img = models.URLField()

# class EDUKASI(models.Model):
#     penjelasan = models.TextField()
#     image = models.ForeignKey(to=IMAGE, null=True, on_delete=models.CASCADE)

# class PENYAKIT(models.Model):
#     nama = models.CharField(max_length=255)
#     kompetensi = models.IntegerField()
#     farmakologi = models.TextField()
#     nonfarmakologi_khusus = models.TextField()
#     edukasi = models.ForeignKey(to=EDUKASI, on_delete=models.CASCADE)

class IDENTITAS(models.Model):
    usia = models.SmallIntegerField()
    berat_badan = models.SmallIntegerField()
    tinggi_badan = models.SmallIntegerField()
    is_cowo = models.BooleanField()
    is_hamil = models.BooleanField()
    is_merokok = models.BooleanField()
    aktivitas = models.SmallIntegerField() # {
        # 1 - Istirahat (tirah baring)
        # 2 - Aktivitas ringan (IRT, pegawai kantor, guru)
        # 3 - Aktivitas sedang (pegawai industri ringan, mahasiswa, militer yang sedang tidak perang)
        # 4 - Aktivitas berat (petani, buruh, atlet, militer dalam keadaan latihan)
        # 5 - Aktivitas sangat berat (tukang becak, tukang gali)
    # }
    alergi = models.TextField(blank=True) # null = true
    stres_metabolik = models.SmallIntegerField() # {
        # 0 - tidak ada
        # 1 - trauma ringan
        # 2 - operasi ringan, trauma sedang
        # 3 - sepsis, operasi besar, trauma berat
    #}
    # penyakit = models.ManyToManyField(to=PENYAKIT)

HomePage/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from . import rumus_basic
from .render_template import *

# Create your views here.
def index(request):
    return render(request, 'home.html')

@login_required(login_url="login:login")
def mulai(request):
    if request.method == 'POST':
        diagnosis = []
        alergi = []
        umur = int(request.POST.get('umur'))
        tb = int(request.POST.get('tb')) #dalam cm
        bb = int(request.POST.get('bb')) #dalam kg
        is_cowo = (request.POST.get('jenis_kelamin') == "True")
        is_merokok = (request.POST.get('is_merokok') == "True")
        is_hamil = (request.POST.get('is_hamil') == "True")
        is_alkohol = (request.POST.get('is_alkohol') == "True")
        diag = request.POST.getlist('diagnosis')
        pekerjaan = int(request.POST.get('pekerjaan'))
        stres_metabolik = int(request.POST.get('stres'))
        aler = request.POST.getlist('alergi')
        pengobatan = request.POST.get('pengobatan')

        is_dewasa = umur > 17

        for val in diag:
            diagnosis.append(val)
        for val in aler:
            alergi.append(val)

        param = {
            'umur': umur,
            'tb': tb,
            'bb': bb,
            'is_cowo': is_cowo,
            'is_hamil': is_hamil,
            'is_merokok':is_merokok,
            'is_alkohol': is_alkohol,
            'diagnosis': diagnosis,
            'pekerjaan': pekerjaan,
            'stres_metabolik': stres_metabolik,
            'alergi': alergi,
            'pengobatan': pengobatan,
            'is_dewasa': is_dewasa,
        }

        rumus_basic.obesitas(param)

        rumus_basic.kalori(param)

        rumus_basic.rekomendasi_olahraga(param)

        rumus_basic.frekuensi_aktivitas(param)

        if("TB" in diagnosis and "DM" in diagnosis and "HP" in diagnosis):
            return DM_TB_HP(request)

        if("TB" in diagnosis and "DM" in diagnosis):
            return DM_TB(request, param)

        if("TB" in diagnosis and "HP" in diagnosis):
            return TB_HP(request, param)

        if("HP" in diagnosis and "DM" in diagnosis):
            return HP_DM(request, param) 

        if("TB" in diagnosis):
            return TB(request, param)

        if("DM" in diagnosis):
            return DM(request, param)

        if("HP" in diagnosis):
            return HP(request, param)

        if("Anemia" in diagnosis):
            return anemia(request, param)

        if("Influenza" in diagnosis):
            return influenza(request, param)

        if("Faringitis" in diagnosis):
            return faringitis(request, param)

        if("Pneumonia" in diagnosis):
            return pneumonia(request, param)

        if("DDR" in diagnosis):
            return diare_dehidrasi_ringan(request, param)
        
        if("DTR" in diagnosis):
            return diare_tanpa_dehidrasi(request, param)

        if("HeadacheAkut" in diagnosis):
            return headache_akut(request, param)
        
        if("HeadacheKronik" in diagnosis):
            return headache_kronis(request, param)

        if("Migrain" in diagnosis):
            return migrain(request, param)
        
    return render(request, 'diagnosis.html')

HomePage/templates/diagnosis.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
Dokuma
{% endblock %}

{% block css %}
<style type="text/css">

    .darkRed {
        color: darkred;
    }

    .darkBlue {
        color: darkblue;
    }

    .navbar {
        position: relative;
        border: 1px solid #080808;
        background-color: #222;
        background-image: linear-gradient(to bottom, #3c3c3c 0, #222 100%);
        background-repeat: repeat-x;
        border-radius: 4px;
        margin: 0;
        padding: 0;
    }

    .navbar-brand {
        float: left;
        padding: 14px 15px;
        font-size: 18px;
        line-height: 20px;
        color: #fff;
        cursor: pointer;
        text-decoration: none;
    }

    a:hover {
        color: #fff;
    }

    .navbar-links {
        font-size: 14px;
        line-height: 20px;
        position: relative;
        margin: 0;
    }

    .navbar-links li {
        cursor: pointer;
        text-decoration: none;
    }

    .navbar-links li {
        display: inline-block;
        min-width: 120px;
        text-align: center;
        margin-top: 15px;
    }

    .navbar-links li.active {
        background-image: #080808;
        background: #080808;
        color: #fff;
        height: 100%;
        padding-top: 15px;
        padding-bottom: 15px;
        margin: 0;
    }

    a {
        color: #9d9d9d;
        cursor: pointer;
        text-decoration: none;
    }

    @media (max-width: 640px) {
        .navbar-brand {
            width: 100%;
        }

        .navbar-links {
            padding-left: 0;
        }

        button.demo {
            margin-right: 100% !important;
        }
    }


    .demo-zone {
        display: block;
        width: 100%;
        min-height: 200px;
    }

    .mini-demo-zone {
        display: block;
        width: 100%;
        min-height: 100px;
    }

    .btns-active,
    .btns-inactive {
        margin-top: 20px;
    }

    label {
        display: inline-block;
        min-width: 220px;
        width: 220px;
    }

    button.demo,
    a.demo {
        margin-right: 0;
        margin-left: 4px;
        text-align: center;
        white-space: nowrap;
        vertical-align: middle;
        user-select: none;
        border-radius: 4px;
        z-index: 1;
        color: #333;
        background: white;
        background-image: linear-gradient(to bottom, #fff 0, #e0e0e0 100%);
        border: 1px solid #ccc !important;
        color: #333;
        line-height: 20px;
        font-size: 14px;
        padding: 4px 12px;
        margin-bottom: 2px;
    }

    button.demo:hover {
        background-image: linear-gradient(to top, #fff 0, #e0e0e0 100%);
    }

</style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/3.5.4/select2.min.css"
    integrity="sha512-iVAPZRCMdOOiZWYKdeY78tlHFUKf/PqAJEf/0bfnkxJ8MHQHqNXB/wK2y6RH/LmoQ0avRlGphSn06IMMxSW+xw=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/3.5.4/select2.min.js"
    integrity="sha512-jfp1Gv+A3dHho9qOUUWOrZA6NWR08j7GYVn8VXcRI0FsDb3xe0hQHVwasi2UarjZzPYOxT5uvmlHrWLXQ+M4AQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"
    integrity="sha512-2ImtlRlf2VVmiGZsjm9bEyhjGW4dU7B6TNwh/hx/iSByxNENtj3WVE6o/9Lj4TJeVXPi4bnOIMXFIJJAeufa0A=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css"
    integrity="sha512-nMNlpuaDPrqlEls3IX/Q56H36qvBASwb3ipuo3MxeWbsQB1881ox0cRv7UPTgBlriqoynt35KjEwgGUeUXIPnw=="
    crossorigin="anonymous" referrerpolicy="no-referrer" /> -->

{% endblock %}

{% block content %}
<!-- ======= Header ======= -->
<header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

        <h1 class="logo me-auto"><a href="{% url 'home:home' %}">Dokuma</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->


        <a href="{% url 'home:home' %}" class="appointment-btn scrollto" style="background-color:#703757"><span
                class="d-none d-md-inline"></span> Home</a>
    </div>
</header><!-- End Header -->
<!-- ======= Appointment Section ======= -->
<section id="appointment" class="appointment section-bg">
    <div class="container">
        <div class="section-title">
            <br><br><br><br>
            <h2>Identitas Pasien</h2>
        </div>

        <form action="" method="POST" role="form" class="">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4 form-group">
                    <input type="text" class="form-control" name="umur" id="umur" placeholder="Umur Pasien" required>
                </div>
                <div class="col-md-4 form-group mt-3 mt-md-0">
                    <input type="text" name="tb" class="form-control" id="tb" placeholder="Tinggi Badan Pasien"
                        required>
                </div>
                <div class="col-md-4 form-group mt-3 mt-md-0">
                    <input type="text" name="bb" class="form-control" id="bb" placeholder="Berat Badan Pasien" required>
                </div>
            </div>

            <div class="row">
                <div class="validate"></div>

                <div class="col-md-4 form-group mt-3 ">
                    <select name="jenis_kelamin" id="jenis_kelamin" class="form-select" required>
                        <option value="">Jenis Kelamin</option>
                        <option value="True">Pria</option>
                        <option value="False">Wanita</option>
                    </select>
                </div>

                <div class="col-md-4 form-group mt-3">
                    <select name="is_hamil" id="is_hamil" class="form-select" required>
                        <option value="">Hamil?</option>
                        <option value="True">Ya</option>
                        <option value="False">Tidak</option>
                    </select>
                </div>
                <div class="col-md-4 form-group mt-3">
                    <select name="is_alkohol" id="is_alkohol" class="form-select" required>
                        <option value="">Alkohol?</option>
                        <option value="True">Ya</option>
                        <option value="False">Tidak</option>
                    </select>
                </div>
            </div>

            <div class="row">
                <div class="col-md-4 form-group mt-3">
                    <select name="is_merokok" id="is_merokok" class="form-select" required>
                        <option value="">Merokok atau Sering Terpapar Rokok?</option>
                        <option value="True">Ya</option>
                        <option value="False">Tidak</option>
                    </select>
                </div>
                <div class="col-md-4 form-group mt-3">
                    <select name="pekerjaan" id="pekerjaan" class="form-select" required>
                        <option value="">Tingkat Aktivitas</option>
                        <option value="1">Istirahat (tirah baring)</option>
                        <option value="2">Aktivitas ringan (IRT, pegawai kantor, guru)</option>
                        <option value="3">Aktivitas sedang (pegawai industri ringan, mahasiswa, militer yang sedang
                            tidak perang)</option>
                        <option value="4">Aktivitas berat (petani, buruh, atlet, militer dalam keadaan latihan)</option>
                        <option value="5">Aktivitas sangat berat (tukang becak, tukang gali)</option>
                    </select>
                </div>
                <div class="col-md-4 form-group mt-3">
                    <select name="stres" id="stres" class="form-select" required>
                        <option value="">Stres Metabolik</option>
                        <option value="0">Tidak ada</option>
                        <option value="1">Trauma ringan</option>
                        <option value="2">Operasi ringan, trauma sedang</option>
                        <option value="3">Sepsis, operasi besar, trauma berat</option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 form-group mt-3">
                    <input type="text" name="pengobatan" class="form-control" id="pengobatan"
                        placeholder="Pengobatan saat ini">
                </div>

                <div class="col-md-4 form-group mt-3">
                    <select id="alergi" name="alergi" multiple="multiple" style="width: 100%" placeholder="Alergi">
                        <option value="Paracetamol">Paracetamol</option>
                        <option value="Ibuprofen">Ibuprofen</option>
                        <option value="Kacang">Kacang</option>
                        <option value="Aspirin">Aspirin</option>
                        <option value="Penisilin">Penisilin, Penicillin</option>
                        <option value="Susu sapi">Susu sapi</option>
                        <option value="Telur">Telur</option>
                        <option value="Kerang">Kerang</option>
                        <option value="Gandum">Gandum</option>
                        <option value="Kecoak">Kecoak</option>
                        <option value="Pewarna">Pewarna</option>
                        <option value="Logam">Logam</option>
                        <option value="Parfum">Parfum</option>
                        <option value="Karet">Karet</option>
                        <option value="Lateks">Lateks</option>
                        <option value="Sengatan lebah">Sengatan lebah</option>
                        <option value="Spora jamur">Spora jamur</option>
                        <option value="Tungau debu rumah">Tungau debu rumah, house dust mite</option>
                        <option value="Pollen">Serbuk sari, Pollen</option>
                        <option value="Ikan">Ikan</option>
                        <option value="Kedelai">Kedelai</option>
                        <option value="Sefalosporin">Sefalosporin/Cephalosporin</option>
                        <option value="NSAID">Nonsteroid Antiinflammatory Drugs, NSAID, Obat anti inflamasi nonsteroid
                            OAINS</option>
                        <option value="Lidokain">Lidocaine, Lidokain</option>
                        <option value="Antikejang">Antikejang, Antiseizure</option>
                        <option value="Metformin">Metformin</option>
                        <option value="Glibenklamid">Glibenklamid, Glibenclamide</option>
                        <option value="Glimepiride">Glimepiride</option>
                        <option value="Glipizid">Glipizid</option>
                        <option value="Rifampisin">Rifampisin, Rifampicin</option>
                        <option value="Isoniazid">Isoniazid</option>
                        <option value="Pirazinamid">Pirazinamid</option>
                        <option value="Etambutol">Etambutol, Ethambutol</option>
                        <option value="Hidroklorotiazid">Hidroklorotiazid, Hydrochlorothiazide</option>
                        <option value="Kaptopril">Kaptopril, Captopril </option>
                        <option value="Amlodipine">Amlodipine</option>
                        <option value="Atenolol">Atenolol</option>
                    </select>
                </div>
                
                <div class="col-md-4 form-group mt-3">
                    <select id="diagnosis" name="diagnosis" multiple="multiple" style="width: 100%" required>
                        <option value="TB">Tuberkulosis paru tanpa komplikasi</option>
                        <option value="HP">Hipertensi esensial</option>
                        <option value="DM">Diabetes melitus tipe 2</option>
                        <option value="Anemia">Anemia</option>
                        <option value="Influenza">Influenza</option>
                        <option value="Faringitis">Faringitis</option>
                        <option value="Pneumonia">Pneumonia</option>
                        <option value="DDR">Diare dehidrasi ringan</option>
                        <option value="DTR">Diare tanpa dehidrasi</option>
                        <option value="HeadacheAkut">Headache Akut</option>
                        <option value="HeadacheKronik">Headache Kronik</option>
                        <option value="Migrain">Migrain</option>
                    </select>
                </div>
            </div>

            <br>
            <div class="text-center"><button type="submit" style="background-color:#703757" style="width: 100%"
                    class="btn btn-primary">Lanjut</button></div>
            <br><br><br><br><br><br><br><br>
        </form>
    </div>
</section><!-- End Appointment Section -->
{% endblock %}

{% block js %}
<script>
    $(document).ready(function () {
        $('#alergi').select2({
            placeholder: "Alergi",
            closeOnSelect: false
        });
        $('#diagnosis').select2({
            placeholder: "Diagnosis",
            closeOnSelect: false
        });
    })
</script>
{% endblock %}

HomePage/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Dokuma
{% endblock %}

{% block content %}
<!-- ======= Header ======= -->
<header id="header" class="fixed-top">
  <div class="container d-flex align-items-center">

    <h1 class="logo me-auto"><a href="{% url 'home:home' %}">Dokuma</a></h1>

    <nav id="navbar" class="navbar order-last order-lg-0">
      <ul>
        <li><a class="nav-link scrollto" style="color:#703757" href="#hero">Home</a></li>
        <!-- <li><a class="nav-link scrollto" href="#counts">Our Partners</a></li>
        <li><a class="nav-link scrollto" href="#testimonials">Testimonials</a></li> -->
        <li><a class="nav-link scrollto" href="#faq">FAQ</a></li> 
        {% if user.is_authenticated %}
        <li><a class="nav-link scrollto" href="{% url 'login:logout' %}">Logout</a></li>
        {% else %}
        <li><a class="nav-link scrollto" href="{% url 'login:login' %}">Login</a></li>
        <li><a class="nav-link scrollto" href="{% url 'register:register' %}">Register</a></li>
        {% endif %}
      </ul>
      <i class="bi bi-list mobile-nav-toggle"></i>
    </nav><!-- .navbar -->

    <a href="{% url 'home:mulai' %}" class="appointment-btn scrollto"><span class="d-none d-md-inline"></span> Mulai </a>

  </div>
</header><!-- End Header -->

<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center">
  <div class="container">
    {% if user.is_authenticated %}
        <h1>Halo, {{user.username}}</h1>
        <h2>Mari kita berikan yang terbaik untuk pasien!</h2>
    {% else %}
        <h1>Welcome to Dokuma</h1>
    {% endif %}
    
    <a href="#why-us" class="btn-get-started scrollto" style="background-color:#703757">Let's Take a Look!</a>
  </div>
</section><!-- End Hero -->

<main id="main">

  <!-- ======= Why Us Section ======= -->
  <section id="why-us" class="why-us">
    <div class="container">

      <div class="row">
        <div class="col-lg-4 d-flex align-items-stretch">
          <div class="content" style="background-color:#703757">
            <h3>Mengapa memilih Dokuma?</h3>
            <p>
              Dokuma adalah website yang dapat mempermudah pencarian tata laksana yang personalized/terindividualisasi berdasarkan data pasien serta diagnosis pasien.
            </p>
            <!-- <div class="text-center">
              <a href="#" class="more-btn">Learn More <i class="bx bx-chevron-right"></i></a>
            </div> -->
          </div>
        </div>
        <div class="col-lg-8 d-flex align-items-stretch">
          <div class="icon-boxes d-flex flex-column justify-content-center">
            <div class="row">
              <div class="col-xl-4 d-flex align-items-stretch">
                <div class="icon-box mt-4 mt-xl-0">
                  <i class="bx bx-receipt" style="color:#703757"></i>
                  <h4>Cepat</h4>
                  <p>Dokuma dapat digunakan langsung di depan pasien!</p>
                </div>
              </div>
              <div class="col-xl-4 d-flex align-items-stretch">
                <div class="icon-box mt-4 mt-xl-0">
                  <i class="bx bx-cube-alt" style="color:#703757"></i>
                  <h4>Kredibel</h4>
                  <p>Dokuma menggunakan sumber yang kredibel dan terupdate</p>
                </div>
              </div>
              <div class="col-xl-4 d-flex align-items-stretch">
                <div class="icon-box mt-4 mt-xl-0">
                  <i class="bx bx-images" style="color:#703757"></i>
                  <h4>Komprehensif</h4>
                  <p>Dokuma memasukkan tata laksana farmakologi, nonfarmakologi, dan edukasi yang lengkap dan terindividualisasi</p>
                </div>
              </div>
            </div>
          </div><!-- End .content-->
        </div>
      </div>

    </div>
  </section><!-- End Why Us Section -->

  <!-- ======= Counts Section ======= -->
  <!-- <section id="counts" class="counts">
    <div class="container">
      <div class="section-title">
        <h2>Our Partners</h2>
      </div>
      <div class="row">

        <div class="col-lg-3 col-md-6">
          <div class="count-box">
            <i class="fas fa-user-md" style="background-color:#703757"></i>
            <span data-purecounter-start="0" data-purecounter-end="85" data-purecounter-duration="1" class="purecounter"></span>
            <p>Doctors</p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 mt-5 mt-md-0">
          <div class="count-box">
            <i class="far fa-hospital" style="background-color:#703757"></i>
            <span data-purecounter-start="0" data-purecounter-end="18" data-purecounter-duration="1" class="purecounter"></span>
            <p>Departments</p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 mt-5 mt-lg-0">
          <div class="count-box">
            <i class="fas fa-flask" style="background-color:#703757"></i>
            <span data-purecounter-start="0" data-purecounter-end="12" data-purecounter-duration="1" class="purecounter"></span>
            <p>Research Labs</p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 mt-5 mt-lg-0">
          <div class="count-box">
            <i class="fas fa-award" style="background-color:#703757"></i>
            <span data-purecounter-start="0" data-purecounter-end="150" data-purecounter-duration="1" class="purecounter"></span>
            <p>Awards</p>
          </div>
        </div>

      </div>

    </div>
  </section> -->
  <!-- End Counts Section -->

  <!-- ======= Doctors Section ======= -->
  <!-- End Doctors Section -->

  <!-- ======= Testimonials Section ======= -->
  <section id="testimonials" class="testimonials">
    
  </section><!-- End Testimonials Section -->

  <!-- ======= Frequently Asked Questions Section ======= -->
  <section id="faq" class="faq section-bg">
    <div class="container">

      <div class="section-title">
        <h2>Frequently Asked Questions</h2>
        <p>Apabila ada pertanyaan yang belum terjawab di sini, mohon tanyakan ke kontak Rheza atau melalui email dokuma@gmail.com</p>
      </div>

      <div class="faq-list">
        <ul>
          <li data-aos="fade-up">
            <i class="bx bx-help-circle icon-help" ></i> <a data-bs-toggle="collapse" data-bs-target="#faq-list-1" class="collapsed">Apakah penyakitnya akan lengkap?<i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
            <div id="faq-list-1" class="collapse" data-bs-parent=".faq-list">
              <p>
                Target awal kami 20 penyakit tersering di FKTP (puskesmas/klinik), lalu bertahap menambahkan penyakit-penyakit kompetensi 4 untuk dokter umum, baru penyakit-penyakit lainnya.
              </p>
            </div>
          </li>

          <li data-aos="fade-up" data-aos-delay="100">
            <i class="bx bx-help-circle icon-help"></i> <a data-bs-toggle="collapse" data-bs-target="#faq-list-2" class="collapsed">Apakah bisa terintegrasi dengan rekam medis online yang sudah ada di FKTP (puskesmas/klinik)?<i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
            <div id="faq-list-2" class="collapse" data-bs-parent=".faq-list">
              <p>
                Saat ini belum karena mengintegrasi dengan pihak lain membutuhkan waktu dan proses yang lebih lama. Saat ini Dokter perlu mengisi secara manual data yang dibutuhkan.
              </p>
            </div>
          </li>

          <li data-aos="fade-up" data-aos-delay="200">
            <i class="bx bx-help-circle icon-help"></i> <a data-bs-toggle="collapse" data-bs-target="#faq-list-3" class="collapsed">Apakah data pasien dapat disimpan? <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
            <div id="faq-list-3" class="collapse" data-bs-parent=".faq-list">
              <p>
                Saat ini belum karena kami akan menghadapi isu etik terkait kerahasiaan data pasien. Namun kami akan berusaha mencarikan solusinya supaya pasien dengan penyakit kronis dapat dimasukkan datanya, sehingga follow up menjadi lebih mudah.
              </p>
            </div>
          </li>

          <li data-aos="fade-up" data-aos-delay="300">
            <i class="bx bx-help-circle icon-help"></i> <a data-bs-toggle="collapse" data-bs-target="#faq-list-4" class="collapsed">Apakah obat-obatan yang dituliskan sudah lengkap? <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
            <div id="faq-list-4" class="collapse" data-bs-parent=".faq-list">
              <p>
                Kami hanya memasukkan obat-obatan yang tersedia di FKTP (puskesmas/klinik) berdasarkan Formularium Nasional Kementerian Kesehatan RI tahun 2019. 
              </p>
            </div>
          </li>

          <li data-aos="fade-up" data-aos-delay="400">
            <i class="bx bx-help-circle icon-help"></i> <a data-bs-toggle="collapse" data-bs-target="#faq-list-5" class="collapsed">Mengapa data hamil, pengobatan saat ini, dan alergi harus diisi? <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
            <div id="faq-list-5" class="collapse" data-bs-parent=".faq-list">
              <p>
                Dokuma mengutakan tata laksana komprehensif yang personalized/terindividualisasi. Data tersebut akan berpengaruh terhadap rekomendasi tata laksana yang akan dimunculkan.
              </p>
            </div>
          </li>

        </ul>
      </div>

    </div>
  </section><!-- End Frequently Asked Questions Section -->
  <!-- ======= Gallery Section ======= -->
  <!-- End Gallery Section -->


</main><!-- End #main -->
{% endblock %}
{% block footer %}
    {% include 'footer.html' %}    
{% endblock %}